name: zenrouter_file_generator
description: "A code generator for file-based routing in Flutter using zenrouter. Generate type-safe routes from your file/directory structure, similar to Next.js or Nuxt.js."
version: 0.3.1
homepage: https://github.com/definev/zenrouter/tree/main/packages/zenrouter_file_generator
repository: https://github.com/definev/zenrouter/tree/main/packages/zenrouter_file_generator
resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Build runner dependencies
  build: ^4.0.3
  source_gen: ^4.1.1
  analyzer: ^8.4.0
  glob: ^2.1.3
  zenrouter_file_annotation: ^0.3.0
  dart_style: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
