name: zenrouter_file_generator_example
description: "An example project for zenrouter_file_generator."
publish_to: 'none'
version: 0.1.0+1

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  zenrouter: 
  zenrouter_devtools: ^0.3.0
  zenrouter_file_annotation: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.10.4
  zenrouter_file_generator:

flutter:
  uses-material-design: true
