name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0-113.0.dev

dependencies:
  flutter:
    sdk: flutter
  
  zenrouter: ^0.2.1
  zenrouter_devtools: ^0.2.0
  zenrouter_file_generator:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.10.4

flutter:
  uses-material-design: true
