name: zenrouter
description: "The Ultimate Flutter Router for Every Navigation Pattern"
version: 0.3.2
homepage: https://github.com/definev/zenrouter/tree/main/packages/zenrouter

environment:
  sdk: ^3.8.0
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: