name: zenrouter
description: >-
  A powerful Flutter router with deep linking, web support, type-safe routing,
  guards, redirects, and zero boilerplate.
version: 0.4.5

repository: https://github.com/definev/zenrouter
homepage: https://github.com/definev/zenrouter/tree/main/packages/zenrouter
issue_tracker: https://github.com/definev/zenrouter/issues
documentation: https://github.com/definev/zenrouter/blob/main/packages/zenrouter/doc/guides/getting-started.md

topics:
  - router
  - navigation
  - routing
  - deep-linking
  - web

screenshots:
  - description: "Zen Logo"
    path: screenshots/logo_light.png

environment:
  sdk: ^3.8.0
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: